# Generated by Django 6.0.5 on 2026-06-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_feedback_fototrabalho_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('barbeiro', 'Barbeiro'), ('administrador', 'Administrador')], default='cliente', max_length=20),
        ),
    ]
