# Generated by Django 6.0.5 on 2026-08-27 01:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_configuracaoestabelecimento_eventowebhookpagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupomDesconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=30, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=150)),
                ('tipo', models.CharField(choices=[('percentual', 'Percentual (%)'), ('fixo', 'Valor Fixo (R$)')], default='percentual', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_minimo_pedido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('limite_usos', models.PositiveIntegerField(blank=True, help_text='Vazio = Ilimitado', null=True)),
                ('usos_atuais', models.PositiveIntegerField(default=0)),
                ('valido_ate', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cupom de Desconto',
                'verbose_name_plural': 'Cupons de Desconto',
                'ordering': ['-criado_em'],
            },
        ),
    ]
