# Generated by Django 6.0.5 on 2026-08-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_categoriadespesa_dadosfiscaisempresa_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Aguardando', 'Cliente Chegou / Aguardando'), ('Em Atendimento', 'Em Atendimento'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado'), ('Não Compareceu', 'Não Compareceu')], db_index=True, default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='fechada_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='status',
            field=models.CharField(choices=[('Aberta', 'Aberta'), ('Fechada', 'Fechada'), ('Cancelada', 'Cancelada')], db_index=True, default='Aberta', max_length=20),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Paga', 'Paga'), ('Cancelada', 'Cancelada')], db_index=True, default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_vencimento',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='data_prevista',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Enviada', 'Enviada'), ('Erro', 'Erro no Envio')], db_index=True, default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('Aguardando', 'Aguardando Pagamento'), ('Pago', 'Pago / Confirmado'), ('Expirado', 'Expirado'), ('Cancelado', 'Cancelado'), ('Reembolsado', 'Reembolsado')], db_index=True, default='Aguardando', max_length=20),
        ),
    ]
