# Generated by Django 5.2.17 on 2026-09-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_alter_agendamento_data_alter_agendamento_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidadebarbearia",
            name="nome",
            field=models.CharField(default="Barber Heitor - Matriz", max_length=200),
        ),
    ]
