# Generated by Django 5.2.17 on 2026-09-10 12:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_alter_unidadebarbearia_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="planoassinatura",
            name="codigo",
            field=models.CharField(
                blank=True,
                help_text="Identificador único (ex: plano-normal, plano-com-barba, plano-cortes-infinitos)",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="planoassinatura",
            name="limite_mensal",
            field=models.PositiveIntegerField(
                blank=True,
                default=4,
                help_text="Limite de atendimentos/visitas por mês (nulo se ilimitado)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="planoassinatura",
            name="modalidade",
            field=models.CharField(
                choices=[
                    ("limitado", "Limitado (X atendimentos/mês)"),
                    ("ilimitado", "Ilimitado (Sem limite mensal)"),
                ],
                default="limitado",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="planoassinatura",
            name="servicos_inclusos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Serviços cobertos no atendimento deste plano",
                related_name="planos_onde_incluso",
                to="website.servico",
            ),
        ),
        migrations.AddField(
            model_name="servico",
            name="codigo",
            field=models.CharField(
                blank=True,
                help_text="Identificador único (ex: cabelo, barba, cavanhaque, sobrancelha)",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="planoassinatura",
            name="desconto_produtos",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="% de desconto em produtos",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="planoassinatura",
            name="quantidade_creditos",
            field=models.PositiveIntegerField(
                default=4, help_text="Cortes/serviços inclusos por mês (legado)"
            ),
        ),
        migrations.CreateModel(
            name="ItemAgendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preco_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Preço congelado no momento da reserva",
                        max_digits=8,
                    ),
                ),
                (
                    "duracao_snapshot",
                    models.PositiveIntegerField(
                        help_text="Duração em minutos congelada no momento da reserva"
                    ),
                ),
                (
                    "coberto_por_assinatura",
                    models.BooleanField(
                        default=False, help_text="Item coberto por plano/assinatura"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "agendamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="website.agendamento",
                    ),
                ),
                (
                    "servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_agendamento",
                        to="website.servico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Agendamento",
                "verbose_name_plural": "Itens de Agendamento",
                "ordering": ["id"],
            },
        ),
    ]
