# Generated by Django 5.2.17 on 2026-09-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0010_planoassinatura_codigo_planoassinatura_limite_mensal_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="barbeiro",
            name="imagem_url",
            field=models.CharField(
                blank=True,
                help_text="URL externa ou caminho estático da foto",
                max_length=500,
            ),
        ),
    ]
