"""
Catálogo do Portfólio Real Barber Heitor (@barber.heitorr).
Centraliza a representação das seis fotografias e três vídeos estáticos
garantindo reusabilidade entre a página inicial e a galeria completa.
"""

PORTFOLIO_ITEMS = [
    {
        "id": "heitor-foto-01",
        "tipo": "imagem",
        "is_video": False,
        "arquivo_static": "website/portfolio/heitor/fotos/corte-01.jpg",
        "capa_static": None,
        "titulo": "Desenho lateral",
        "alt": "Corte com desenho na lateral, fotografado na cadeira da barbearia.",
        "descricao": "Corte com desenho na lateral, fotografado na cadeira da barbearia.",
        "largura": 1536,
        "altura": 2048,
        "ordem": 1,
        "categoria": "Cortes",
        "categoria_filtro": "fotos",
        "duracao_formatada": None,
    },
    {
        "id": "heitor-foto-02",
        "tipo": "imagem",
        "is_video": False,
        "arquivo_static": "website/portfolio/heitor/fotos/corte-02.jpg",
        "capa_static": None,
        "titulo": "Vista lateral",
        "alt": "Corte com transição de comprimentos na lateral, em vista de perfil.",
        "descricao": "Corte com transição de comprimentos na lateral, em vista de perfil.",
        "largura": 1440,
        "altura": 1920,
        "ordem": 2,
        "categoria": "Cortes",
        "categoria_filtro": "fotos",
        "duracao_formatada": None,
    },
    {
        "id": "heitor-foto-03",
        "tipo": "imagem",
        "is_video": False,
        "arquivo_static": "website/portfolio/heitor/fotos/corte-03.jpg",
        "capa_static": None,
        "titulo": "Topo e parte posterior",
        "alt": "Corte com topo e parte posterior mais longos, em vista lateral.",
        "descricao": "Corte com topo e parte posterior mais longos, em vista lateral.",
        "largura": 1536,
        "altura": 2048,
        "ordem": 3,
        "categoria": "Cortes",
        "categoria_filtro": "fotos",
        "duracao_formatada": None,
    },
    {
        "id": "heitor-foto-04",
        "tipo": "imagem",
        "is_video": False,
        "arquivo_static": "website/portfolio/heitor/fotos/corte-04.jpg",
        "capa_static": None,
        "titulo": "Desenho na parte posterior",
        "alt": "Detalhe do desenho na parte posterior do corte.",
        "descricao": "Detalhe do desenho na parte posterior do corte.",
        "largura": 1440,
        "altura": 1920,
        "ordem": 4,
        "categoria": "Cortes",
        "categoria_filtro": "fotos",
        "duracao_formatada": None,
    },
    {
        "id": "heitor-foto-05",
        "tipo": "imagem",
        "is_video": False,
        "arquivo_static": "website/portfolio/heitor/fotos/corte-05.jpg",
        "capa_static": None,
        "titulo": "Detalhe do corte",
        "alt": "Vista lateral e superior de um corte realizado na barbearia.",
        "descricao": "Vista lateral e superior de um corte realizado na barbearia.",
        "largura": 1536,
        "altura": 2048,
        "ordem": 5,
        "categoria": "Cortes",
        "categoria_filtro": "fotos",
        "duracao_formatada": None,
    },
    {
        "id": "heitor-foto-06",
        "tipo": "imagem",
        "is_video": False,
        "arquivo_static": "website/portfolio/heitor/fotos/corte-06.jpg",
        "capa_static": None,
        "titulo": "Acabamento lateral",
        "alt": "Vista lateral do corte, com acabamento na nuca.",
        "descricao": "Vista lateral do corte, com acabamento na nuca.",
        "largura": 1179,
        "altura": 1571,
        "ordem": 6,
        "categoria": "Cortes",
        "categoria_filtro": "fotos",
        "duracao_formatada": None,
    },
    {
        "id": "heitor-video-01",
        "tipo": "video",
        "is_video": True,
        "arquivo_static": "website/portfolio/heitor/videos/corte-01.mp4",
        "capa_static": "website/portfolio/heitor/capas/video-01.jpg",
        "titulo": "Corte em vídeo 01",
        "alt": "Registro em vídeo do portfólio de cortes realizados na barbearia, clipe 01.",
        "descricao": "Registro em vídeo do portfólio de cortes realizados na barbearia, clipe 01.",
        "largura": 720,
        "altura": 960,
        "ordem": 7,
        "categoria": "Vídeos",
        "categoria_filtro": "videos",
        "duracao_formatada": "15s",
    },
    {
        "id": "heitor-video-02",
        "tipo": "video",
        "is_video": True,
        "arquivo_static": "website/portfolio/heitor/videos/corte-02.mp4",
        "capa_static": "website/portfolio/heitor/capas/video-02.jpg",
        "titulo": "Corte em vídeo 02",
        "alt": "Registro em vídeo do portfólio de cortes realizados na barbearia, clipe 02.",
        "descricao": "Registro em vídeo do portfólio de cortes realizados na barbearia, clipe 02.",
        "largura": 720,
        "altura": 960,
        "ordem": 8,
        "categoria": "Vídeos",
        "categoria_filtro": "videos",
        "duracao_formatada": "8s",
    },
    {
        "id": "heitor-video-03",
        "tipo": "video",
        "is_video": True,
        "arquivo_static": "website/portfolio/heitor/videos/corte-03.mp4",
        "capa_static": "website/portfolio/heitor/capas/video-03.jpg",
        "titulo": "Corte em vídeo 03",
        "alt": "Registro em vídeo do portfólio de cortes realizados na barbearia, clipe 03.",
        "descricao": "Registro em vídeo do portfólio de cortes realizados na barbearia, clipe 03.",
        "largura": 720,
        "altura": 960,
        "ordem": 9,
        "categoria": "Vídeos",
        "categoria_filtro": "videos",
        "duracao_formatada": "9s",
    },
]


def get_portfolio_items(tipo=None, limite=None):
    """
    Retorna a lista de itens do portfólio Barber Heitor.
    Opcionalmente filtra por tipo ('imagem' | 'video') e limita a quantidade.
    """
    items = list(PORTFOLIO_ITEMS)
    if tipo:
        items = [i for i in items if i["tipo"] == tipo]
    if limite:
        items = items[:limite]
    return items
