"""
Catálogo do Portfólio Real Barber Heitor (@barber.heitorr).
Centraliza a representação das seis fotografias e três vídeos estáticos
garantindo reusabilidade entre a página inicial e a galeria completa.
"""

PORTFOLIO_ITEMS = [
    {
        "id": "heitor-foto-01",
        "tipo": "imagem",
        "is_video": False,
        "arquivo_static": "website/portfolio/heitor/fotos/corte-01.jpg",
        "capa_static": None,
        "titulo": "Mid Fade com Desenho Lateral",
        "alt": "Corte degradê médio com risco estilizado na lateral e acabamento na navalha.",
        "descricao": "Degradê médio (Mid Fade) com desenho freestyle na lateral e topo texturizado.",
        "largura": 1536,
        "altura": 2048,
        "ordem": 1,
        "categoria": "Cortes",
        "categoria_filtro": "fotos",
        "duracao_formatada": None,
    },
    {
        "id": "heitor-foto-02",
        "tipo": "imagem",
        "is_video": False,
        "arquivo_static": "website/portfolio/heitor/fotos/corte-02.jpg",
        "capa_static": None,
        "titulo": "Taper Fade Alinhado",
        "alt": "Corte Taper Fade com transição suave e pezinho na régua.",
        "descricao": "Taper Fade clássico com disfarce limpo nas costeletas e nuca alinhada na navalha.",
        "largura": 1440,
        "altura": 1920,
        "ordem": 2,
        "categoria": "Cortes",
        "categoria_filtro": "fotos",
        "duracao_formatada": None,
    },
    {
        "id": "heitor-foto-03",
        "tipo": "imagem",
        "is_video": False,
        "arquivo_static": "website/portfolio/heitor/fotos/corte-03.jpg",
        "capa_static": None,
        "titulo": "Mullet Fade Moderno",
        "alt": "Corte Mullet Fade moderno com laterais disfarçadas e volume no topo.",
        "descricao": "Mullet contemporâneo com laterais na zero, disfarce limpo e caimento natural.",
        "largura": 1536,
        "altura": 2048,
        "ordem": 3,
        "categoria": "Cortes",
        "categoria_filtro": "fotos",
        "duracao_formatada": None,
    },
    {
        "id": "heitor-foto-04",
        "tipo": "imagem",
        "is_video": False,
        "arquivo_static": "website/portfolio/heitor/fotos/corte-04.jpg",
        "capa_static": None,
        "titulo": "Freestyle Navalhado na Nuca",
        "alt": "Detalhe de desenho freestyle na nuca com acabamento na navalha.",
        "descricao": "Linhas freestyle personalizadas na nuca com transição em degradê e acabamento milimétrico.",
        "largura": 1440,
        "altura": 1920,
        "ordem": 4,
        "categoria": "Cortes",
        "categoria_filtro": "fotos",
        "duracao_formatada": None,
    },
    {
        "id": "heitor-foto-05",
        "tipo": "imagem",
        "is_video": False,
        "arquivo_static": "website/portfolio/heitor/fotos/corte-05.jpg",
        "capa_static": None,
        "titulo": "Moica Disfarçado",
        "alt": "Corte moicano disfarçado com degradê e topo texturizado.",
        "descricao": "Moica (moicano disfarçado) com degradê em V na nuca, laterais limpas e textura expressiva.",
        "largura": 1536,
        "altura": 2048,
        "ordem": 5,
        "categoria": "Cortes",
        "categoria_filtro": "fotos",
        "duracao_formatada": None,
    },
    {
        "id": "heitor-foto-06",
        "tipo": "imagem",
        "is_video": False,
        "arquivo_static": "website/portfolio/heitor/fotos/corte-06.jpg",
        "capa_static": None,
        "titulo": "Pezinho na Régua e Acabamento",
        "alt": "Acabamento de pezinho alinhado na régua com nuca limpa.",
        "descricao": "Alinhamento de contorno e pezinho na navalha descartável com transição suave.",
        "largura": 1179,
        "altura": 1571,
        "ordem": 6,
        "categoria": "Cortes",
        "categoria_filtro": "fotos",
        "duracao_formatada": None,
    },
    {
        "id": "heitor-video-01",
        "tipo": "video",
        "is_video": True,
        "arquivo_static": "website/portfolio/heitor/videos/corte-01.mp4",
        "capa_static": "website/portfolio/heitor/capas/video-01.jpg",
        "titulo": "Corte Americano",
        "alt": "Demonstração do Corte Americano com Taper Fade e finalização na tesoura.",
        "descricao": "Corte estilo Americano completo: degradê nas têmporas e nuca, textura no topo e pezinho na régua.",
        "largura": 720,
        "altura": 960,
        "ordem": 7,
        "categoria": "Vídeos",
        "categoria_filtro": "videos",
        "duracao_formatada": "15s",
    },
    {
        "id": "heitor-video-02",
        "tipo": "video",
        "is_video": True,
        "arquivo_static": "website/portfolio/heitor/videos/corte-02.mp4",
        "capa_static": "website/portfolio/heitor/capas/video-02.jpg",
        "titulo": "Corte do Jaca",
        "alt": "Demonstração do Corte do Jaca com degradê baixo disfarçado.",
        "descricao": "Corte do Jaca carioca tradicional: disfarce baixo na zero com transição suave e contornos limpos.",
        "largura": 720,
        "altura": 960,
        "ordem": 8,
        "categoria": "Vídeos",
        "categoria_filtro": "videos",
        "duracao_formatada": "8s",
    },
    {
        "id": "heitor-video-03",
        "tipo": "video",
        "is_video": True,
        "arquivo_static": "website/portfolio/heitor/videos/corte-03.mp4",
        "capa_static": "website/portfolio/heitor/capas/video-03.jpg",
        "titulo": "Degradê Navalhado e Barba",
        "alt": "Demonstração de Low Fade navalhado combinado com barba alinhada.",
        "descricao": "Degradê navalhado Low Fade com alinhamento perfeito entre as costeletas e a barba desenhada.",
        "largura": 720,
        "altura": 960,
        "ordem": 9,
        "categoria": "Vídeos",
        "categoria_filtro": "videos",
        "duracao_formatada": "9s",
    },
]


def get_portfolio_items(tipo=None, limite=None):
    """
    Retorna a lista de itens do portfólio Barber Heitor.
    Opcionalmente filtra por tipo ('imagem' | 'video') e limita a quantidade.
    """
    items = list(PORTFOLIO_ITEMS)
    if tipo:
        items = [i for i in items if i["tipo"] == tipo]
    if limite:
        items = items[:limite]
    return items
